import { useEffect } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";

const NotFound = () => {
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    console.error("404 Error: User attempted to access non-existent route:", location.pathname);
  }, [location.pathname]);

  return (
    <section className="min-h-screen relative overflow-hidden bg-background text-foreground">
      <div
        className="absolute inset-0 pointer-events-none opacity-[0.03]"
        style={{
          backgroundImage:
            "repeating-linear-gradient(0deg, transparent, transparent 2px, hsl(var(--foreground)) 2px, hsl(var(--foreground)) 3px)",
        }}
      />

      {/* Decorative blocks */}
      <div
        className="absolute top-16 right-10 w-24 h-24 brutal-border hidden md:block"
        style={{ background: "hsl(var(--neon-green))", transform: "rotate(-11deg)" }}
      />
      <div
        className="absolute bottom-44 left-8 w-28 h-28 brutal-border hidden md:block"
        style={{
          backgroundImage:
            "radial-gradient(hsl(var(--foreground)) 1px, transparent 1px)",
          backgroundSize: "8px 8px",
          transform: "rotate(6deg)",
        }}
      />

      <div className="container mx-auto px-6 pt-24 pb-28 relative z-10 min-h-screen flex items-center">
        <div className="w-full grid lg:grid-cols-[1.1fr_0.9fr] gap-8 items-end">
          <div>
            <div className="relative">
              <h1 className="text-[7rem] leading-none md:text-[11rem] lg:text-[14rem] font-heading font-bold tracking-tight">
                404
              </h1>
              <div
                className="absolute left-0 -bottom-2 h-2 w-40 brutal-border"
                style={{ background: "hsl(var(--foreground))" }}
              />
            </div>

            <div className="mt-4 brutal-border brutal-shadow p-5 max-w-xl bg-foreground text-background">
              <p className="text-4xl md:text-6xl font-heading font-bold leading-none uppercase">
                Lost In The Void
              </p>
              <p className="mt-4 text-base md:text-2xl font-mono leading-snug text-background/90">
                The page you are looking for has been redacted, relocated, or never existed in this
                dimension. Stay calm.
              </p>
            </div>
          </div>

          <div className="brutal-border brutal-shadow-lg p-5 bg-background max-w-xl ml-auto">
            <div
              className="inline-block brutal-border px-3 py-1 text-xs md:text-sm font-mono font-bold uppercase -mt-9 mb-4"
              style={{ background: "hsl(var(--destructive))", color: "hsl(var(--destructive-foreground))" }}
            >
              Critical Error
            </div>

            <p className="font-mono text-xs md:text-sm uppercase mb-4">Trace ID: RDCTD-99X-VOID</p>
            <p className="text-lg md:text-2xl font-mono leading-snug mb-6">
              We cannot find the page you are looking for. It may have been moved, renamed, or
              deleted. Use the options below to safely return to an active route.
            </p>

            <div className="flex flex-col gap-3">
              <Link to="/" className="brutal-btn-neon text-center text-xl">
                Go Home
              </Link>
              <button
                type="button"
                onClick={() => navigate(-1)}
                className="brutal-btn bg-background text-foreground text-xl"
              >
                Go Back
              </button>
            </div>

            <p className="mt-6 font-mono text-xs uppercase text-muted-foreground">
              This error was generated by the radical editorial engine v4.0.4
            </p>
          </div>
        </div>
      </div>

      <div
        className="absolute bottom-0 left-0 right-0 brutal-border-thick border-l-0 border-r-0 py-3 overflow-hidden"
        style={{ background: "hsl(var(--neon-blue))", color: "hsl(var(--neon-blue-foreground))" }}
      >
        <div className="marquee whitespace-nowrap font-mono text-sm md:text-xl font-bold tracking-widest uppercase">
          <span className="mx-8">Unknown Protocol</span>
          <span className="mx-8">⚠ System Failure</span>
          <span className="mx-8">⊙ Data Redacted</span>
          <span className="mx-8">⊘ Lost In Space</span>
          <span className="mx-8">Unknown Protocol</span>
          <span className="mx-8">⚠ System Failure</span>
          <span className="mx-8">⊙ Data Redacted</span>
          <span className="mx-8">⊘ Lost In Space</span>
        </div>
      </div>
    </section>
  );
};

export default NotFound;
